---
language: python
sudo: required
dist: trusty
cache:
  directories: [ '$HOME/lxc' ]
  pip: true
env:
# The following default to Debian Stretch
- ANSIBLE_VERSION='git+https://github.com/ansible/ansible.git@devel' # 2.6 DEVEL
- ANSIBLE_VERSION='ansible>=2.5.0,<2.6.0' # 2.5.x
- ANSIBLE_VERSION='ansible>=2.4.0,<2.5.0' # 2.4.x
- ANSIBLE_VERSION='ansible>=2.3.0,<2.4.0' # 2.3.x
- LXC_DISTRO=debian LXC_RELEASE=jessie
- LXC_DISTRO=ubuntu LXC_RELEASE=trusty
- LXC_DISTRO=ubuntu LXC_RELEASE=xenial
- LXC_DISTRO=centos LXC_RELEASE=7
- LXC_DISTRO=fedora LXC_RELEASE=26
- LXC_DISTRO=fedora LXC_RELEASE=27
matrix:
  fast_finish: true
before_cache:
- 'sudo mkdir $HOME/lxc && sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/ &&
  sudo chown $USER: $HOME/lxc/cache.tar'
install:
- sudo tar xf $HOME/lxc/cache.tar -C / || true
- sudo apt-get install -y expect-dev
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../\ncallback_whitelist=profile_tasks' >ansible.cfg
- ansible-galaxy install lae.travis-lxc
- ansible-playbook -vvv tests/install.yml -i tests/inventory
script:
- ansible-playbook tests/deploy.yml -i tests/inventory --syntax-check
- ansible-playbook tests/deploy.yml -i tests/inventory
- 'ANSIBLE_STDOUT_CALLBACK=debug unbuffer ansible-playbook -vv tests/deploy.yml
  -i tests/inventory >/tmp/idempotency.log 2>&1 ||
  (e=$?; cat /tmp/idempotency.log; exit $e)'
- 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" &&
  (echo "Idempotence: PASS"; exit 0) ||
  (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)'
- ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -v tests/test.yml -i tests/inventory
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
